/**
 * ANDRIX® 2020-2025
 */

using UnityEngine;

[System.Serializable]
public struct DEXyznData
{
	public DEXyznData(int size)
	{
		data = new DEXyznBit[size];
		title = "Growth data generated by Alex Andrix based on creation Unexplored Space Eaters 3D";
		version = "1.1";
		date = "2025-07-02";
	}

	public string title;
	public string version;
	public string date;
	public DEXyznBit[] data;
}
