/**
 * Alex Andrix © 2020-2024
 */

using UnityEngine;

[System.Serializable]
public struct GrowthData
{
	public GrowthData(int size)
	{
		data = new GrowthBit[size];
		title = "Growth data generated by Alex Andrix based on creation Unexplored Space Eaters 3D";
		version = "1.0";
		date = "2024-03-03";
	}

	public string title;
	public string version;
	public string date;
	public GrowthBit[] data;
}
